plugins:
  - prettier
extends:
  - next/core-web-vitals
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

rules:
  linebreak-style: 'off'
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence:
    - 'error'
    - props: 'never'
      children: 'never'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  react/no-children-prop: off
  prettier/prettier:
    - error
    - endOfLine: auto
